### ISSUE TITLE
ModuleNotFoundError: No module named 'libKeOpstorch20877e0caa'

### ISSUE THREAD

**Issue by Rick-960123** [drprojects/DeepViewAgg#8] opened 2022-07-13 02:14 UTC
Compiling libKeOpstorch3001cb3e02 in /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02:
       formula: ArgKMin_Reduction(Sum(Square((Var(0,3,0) - Var(1,3,1)))),50,0)
       aliases: Var(0,3,0); Var(1,3,1); 
       dtype  : float32
... /home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/autodiff/BinaryOp.h(46): error: too many arguments for template template parameter "OP"
          detected during:
            instantiation of class "keops::BinaryOp_base<OP, FA, FB, PARAMS...> [with OP=keops::Subtract_Impl, FA=keops::Var<0, 3, 0>, FB=keops::Var<1, 3, 1>, PARAMS=<>]" 
(113): here
            instantiation of class "keops::BinaryOp<OP, keops::Var<NA, DIMA, CATA>, keops::Var<NB, DIMB, CATB>, PARAMS...> [with OP=keops::Subtract_Impl, NA=0, DIMA=3, CATA=0, NB=1, DIMB=3, CATB=1, PARAMS=<>]" 
/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/formulas/maths/Subtract.h(31): here
            instantiation of class "keops::Subtract_Impl<FA, FB> [with FA=keops::Var<0, 3, 0>, FB=keops::Var<1, 3, 1>]" 
/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/pre_headers.h(40): here
            instantiation of class "keops::KeopsNS<F> [with F=keops::CondType<keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::CondType<keops::Add_Impl_Broadcast<keops::Minus<keops::Var<1, 3, 1>>, keops::Var<0, 3, 0>>, keops::CondType<keops::Subtract_Impl_Broadcast<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, false>, false>, true>]" 
/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/libKeOpstorch3001cb3e02.h(27): here

/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/autodiff/UnaryOp.h(50): error: too many arguments for template template parameter "OP"
          detected during:
            instantiation of class "keops::UnaryOp_base<OP, F, NS...> [with OP=keops::Square, F=keops::CondType<keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::CondType<keops::Add_Impl_Broadcast<keops::Minus<keops::Var<1, 3, 1>>, keops::Var<0, 3, 0>>, keops::CondType<keops::Subtract_Impl_Broadcast<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, false>, false>, true>, NS=<>]" 
(61): here
            instantiation of class "keops::UnaryOp<OP, F, NS...> [with OP=keops::Square, F=keops::CondType<keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::CondType<keops::Add_Impl_Broadcast<keops::Minus<keops::Var<1, 3, 1>>, keops::Var<0, 3, 0>>, keops::CondType<keops::Subtract_Impl_Broadcast<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, false>, false>, true>, NS=<>]" 
/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/formulas/maths/Square.h(23): here
            instantiation of class "keops::Square<F> [with F=keops::CondType<keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::CondType<keops::Add_Impl_Broadcast<keops::Minus<keops::Var<1, 3, 1>>, keops::Var<0, 3, 0>>, keops::CondType<keops::Subtract_Impl_Broadcast<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, false>, false>, true>]" 
/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/pre_headers.h(40): here
            instantiation of class "keops::KeopsNS<F> [with F=keops::Square<keops::CondType<keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::CondType<keops::Add_Impl_Broadcast<keops::Minus<keops::Var<1, 3, 1>>, keops::Var<0, 3, 0>>, keops::CondType<keops::Subtract_Impl_Broadcast<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, keops::Subtract_Impl<keops::Var<0, 3, 0>, keops::Var<1, 3, 1>>, false>, false>, true>>]" 
/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/libKeOpstorch3001cb3e02.h(27): here

2 errors detected in the compilation of "/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/link_autodiff.cu".
CMake Error at keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o

make[3]: *** [CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/build.make:65：CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o] 错误 1
make[2]: *** [CMakeFiles/Makefile2:298：CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:252：CMakeFiles/libKeOpstorch3001cb3e02.dir/rule] 错误 2
make: *** [Makefile:183：libKeOpstorch3001cb3e02] 错误 2

--------------------- MAKE DEBUG -----------------
Command '['cmake', '--build', '.', '--target', 'libKeOpstorch3001cb3e02', '--', 'VERBOSE=1']' returned non-zero exit status 2.
/usr/bin/cmake -S/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops -B/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/make -f CMakeFiles/Makefile2 libKeOpstorch3001cb3e02
make[1]: 进入目录“/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02”
/usr/bin/cmake -S/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops -B/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles 4
/usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/libKeOpstorch3001cb3e02.dir/all
make[2]: 进入目录“/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02”
/usr/bin/make -f CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/build.make CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/depend
make[3]: 进入目录“/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02”
[ 25%] Building NVCC (Device) object CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o
cd /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core && /usr/bin/cmake -E make_directory /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/.
cd /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core && /usr/bin/cmake -D verbose:BOOL=1 -D build_configuration:STRING=Release -D generated_file:STRING=/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o -D generated_cubin_file:STRING=/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.cubin.txt -P /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.Release.cmake
-- Removing /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o
/usr/bin/cmake -E remove /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o
-- Generating dependency file: /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.NVCC-depend
/usr/local/cuda-11.4/bin/nvcc -M -D__CUDACC__ /home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/link_autodiff.cu -o /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.NVCC-depend -m64 -DkeopslibKeOpstorch3001cb3e02_EXPORTS -DMAXIDGPU=0 -DMAXTHREADSPERBLOCK0=1024 -DSHAREDMEMPERBLOCK0=49152 -D_FORCE_INLINES -DCUDA_BLOCK_SIZE=192 -DUSE_CUDA=1 -D__TYPE__=float -DC_CONTIGUOUS=1 -DMODULE_NAME=libKeOpstorch3001cb3e02 -DUSE_DOUBLE=0 -DKERNEL_GEOM_TYPE=0 -DKERNEL_SIG_TYPE=0 -DKERNEL_SPHERE_TYPE=0 -DMODULE_NAME_FSHAPE_SCP=fshape_scp_gaussiangaussiangaussian_unoriented_float -Xcompiler ,\"-Wall\",\"-Wno-unknown-pragmas\",\"-fmax-errors=2\",\"-fPIC\",\"-O3\",\"-DNDEBUG\",\"-O3\" -gencode arch=compute_75,code=sm_75 --use_fast_math --compiler-options=-fPIC -ccbin /usr/bin/c++ --pre-include=libKeOpstorch3001cb3e02.h -DNVCC -I/usr/local/cuda-11.4/include -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops -I/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02 -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/include -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/include/torch/csrc/api/include
-- Generating temporary cmake readable file: /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend.tmp
/usr/bin/cmake -D input_file:FILEPATH=/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.NVCC-depend -D output_file:FILEPATH=/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend.tmp -D verbose=1 -P /usr/share/cmake-3.16/Modules/FindCUDA/make2cmake.cmake
-- Copy if different /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend.tmp to /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend
/usr/bin/cmake -E copy_if_different /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend.tmp /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend
-- Removing /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend.tmp and /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.NVCC-depend
/usr/bin/cmake -E remove /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.depend.tmp /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o.NVCC-depend
-- Generating /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o
/usr/local/cuda-11.4/bin/nvcc /home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops/core/link_autodiff.cu -c -o /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o -m64 -DkeopslibKeOpstorch3001cb3e02_EXPORTS -DMAXIDGPU=0 -DMAXTHREADSPERBLOCK0=1024 -DSHAREDMEMPERBLOCK0=49152 -D_FORCE_INLINES -DCUDA_BLOCK_SIZE=192 -DUSE_CUDA=1 -D__TYPE__=float -DC_CONTIGUOUS=1 -DMODULE_NAME=libKeOpstorch3001cb3e02 -DUSE_DOUBLE=0 -DKERNEL_GEOM_TYPE=0 -DKERNEL_SIG_TYPE=0 -DKERNEL_SPHERE_TYPE=0 -DMODULE_NAME_FSHAPE_SCP=fshape_scp_gaussiangaussiangaussian_unoriented_float -Xcompiler ,\"-Wall\",\"-Wno-unknown-pragmas\",\"-fmax-errors=2\",\"-fPIC\",\"-O3\",\"-DNDEBUG\",\"-O3\" -gencode arch=compute_75,code=sm_75 --use_fast_math --compiler-options=-fPIC -ccbin /usr/bin/c++ --pre-include=libKeOpstorch3001cb3e02.h -DNVCC -I/usr/local/cuda-11.4/include -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/pykeops/keops -I/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02 -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/include -I/home/kilox/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/include/torch/csrc/api/include
-- Removing /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o
/usr/bin/cmake -E remove /home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02/CMakeFiles/keopslibKeOpstorch3001cb3e02.dir/keops/core/./keopslibKeOpstorch3001cb3e02_generated_link_autodiff.cu.o
make[3]: 离开目录“/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02”
make[2]: 离开目录“/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02”
make[1]: 离开目录“/home/kilox/.cache/pykeops-1.3-cpython-37/build-libKeOpstorch3001cb3e02”

--------------------- ----------- -----------------
Done.

**Comment by Rick-960123** [comment] 2022-07-13 02:32
I have solved this trouble by cmd 'pip install pykeops ==1.4.1'

**Comment by drprojects** [comment] 2022-07-13 09:49
Hi @Rick-960123, this is a duplicate of https://github.com/drprojects/DeepViewAgg/issues/7.

You seem to have both come to the same conclusion that manually reinstalling `pykeops` solves the problem. I know this error is system-dependent (usually connected to the CUDA and gcc versions you have on your machine), so I keep your suggested fix in mind but will not change the `pykeops` version in `install.sh` for now.

Closing this issue for now.

**Closed as completed** 2022-07-13 09:49 UTC
